#!/usr/bin/env python
"""Build a self-contained synthetic experiment: captions, config, nothing else.

    python scripts/make_dryrun_config.py --root /tmp/fiber_dryrun

The config is the PRODUCTION config with sizes, dimensions and paths shrunk -- not a
hand-written copy. A copied fixture drifts: a key added to configs/linear_fiber.yaml
would be missing here and the dry run would stop covering the path that reads it.

Everything it produces is a plumbing fixture. The pixels come from
cache_native_dataset.py --synthetic and are stamped as such.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

from fiber.utils.config import load_config

N_TRAIN_CAPTIONS, N_HELDOUT_CAPTIONS = 600, 200


def _plain(obj):
    """load_config returns Config (a dict subclass) and records where each default came
    from under underscore keys. yaml.safe_dump can represent neither."""
    if isinstance(obj, dict):
        return {k: _plain(v) for k, v in obj.items() if not str(k).startswith("_")}
    if isinstance(obj, list):
        return [_plain(v) for v in obj]
    return obj


def _captions(n: int, prefix: str) -> dict:
    # Unique, >= 8 characters, no newlines: exactly what load_captions keeps.
    return {"annotations": [{"caption": f"{prefix} synthetic caption number {i:05d}"}
                            for i in range(n)]}


def build(root: Path, src_config: str = "configs/linear_fiber.yaml") -> Path:
    root = Path(root).resolve()
    (root / "prompts").mkdir(parents=True, exist_ok=True)
    (root / "reports").mkdir(parents=True, exist_ok=True)
    train_caps = root / "prompts" / "captions_train.json"
    heldout_caps = root / "prompts" / "captions_heldout.json"
    train_caps.write_text(json.dumps(_captions(N_TRAIN_CAPTIONS, "train")))
    heldout_caps.write_text(json.dumps(_captions(N_HELDOUT_CAPTIONS, "heldout")))

    cfg = _plain(load_config(src_config))

    # sizes: train must stay big enough that A_teacher / A_operator / B are all
    # non-empty after the two-way cross-fit split, i.e. >= ~4 per role.
    cfg["dataset"] = {**cfg["dataset"],
                      "root": str(root / "cache"),
                      "splits": {"train": 96, "val": 48, "test": 48},
                      "pilot": {"train": 96, "val": 48, "test": 48},
                      "prompts": {**cfg["dataset"]["prompts"],
                                  "source": str(train_caps),
                                  "heldout_source": str(heldout_caps)}}
    # d = 256, so k = 8 leaves the Grassmann count m(d-1) >= k(d-k) satisfiable
    cfg["latent"] = {"channels": 4, "height": 8, "width": 8, "dim": 256}
    cfg["model"] = {**cfg["model"], "resolution": 64, "dtype": "float32", "device": "cpu"}
    cfg["extractor"] = {**cfg["extractor"], "in_resolution": 64}
    cfg["fiber"] = {**cfg["fiber"], "robust_dims": 8,
                    "required_arms": ["C2_haar", "D_spectral"],
                    "arms": {"C2_haar": {"type": "haar", "seeds": [0, 1]},
                             "D_spectral": {"type": "spectral_topk", "seeds": [0]}},
                    "reflectors_by_k": {8: 16}}
    cfg["training"] = {**cfg["training"], "epochs": 2, "batch_size": 8,
                       "warmup_steps": 5, "amp": False}
    cfg["spectrum"] = {**cfg["spectrum"], "certification_bootstrap": 100}
    cfg["eval"] = {**cfg["eval"], "bootstrap_resamples": 200}
    cfg["train_attacks"] = ["clean", "jpeg50", "resize050", "noise010", "blur20"]
    cfg["eval_attacks"] = ["clean", "jpeg50", "resize050", "noise010", "blur20"]
    cfg["paths"] = {**cfg["paths"], "data_root": str(root),
                    "cache_dir": str(root / "cache"),
                    "reports_dir": str(root / "reports")}
    cfg["determinism"] = {**cfg["determinism"], "cudnn_deterministic": False}

    out = root / "dryrun.yaml"
    out.write_text("# GENERATED by scripts/make_dryrun_config.py -- plumbing fixture, "
                   "not an experiment.\n" + yaml.safe_dump(cfg, sort_keys=True))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", required=True)
    ap.add_argument("--config", default="configs/linear_fiber.yaml")
    args = ap.parse_args()
    print(build(Path(args.root), args.config))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
